workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-terraform

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a

  coverage:
    image: coverage
    when:
      branch: master

  latest:
    image: docker
    repo: plugins/drone-terraform
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

plugin:
  name: Terraform
  desc: Execute Terraform plan and apply
  type: deploy
  image: plugins/drone-terraform
  labels:
    - terraform
